apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs
  namespace: midawson
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:edd8bf28d09df2b95e8a0275c4f835f08ac8e13985e449e8393c5637f7254b09
        name: container-image
        resources: {}
status: {}
