apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: nodejs-2
  namespace: midawson
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: michael-scenario2
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: nodejs-2
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: nodejs-2-
      labels:
        build.appstudio.openshift.io/application: michael-scenario2
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: nodejs-2
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: midawson
    spec:
      params:
      - name: git-url
        value: https://github.com/maysunfaisal/multi-components-dockerfile
      - name: output-image
        value: quay.io/redhat-appstudio/user-workload:midawson-nodejs-2-$(tt.params.git-revision)
      - name: dockerfile
        value: https://raw.githubusercontent.com/nodeshift-starters/devfile-sample/main/Dockerfile
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:13f5d9c921b3f727684a00084037f673a0dc4273
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: nodejs-2/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
